# Generated by Django 4.2.1 on 2023-05-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_category_title_alter_region_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vacancy.category'),
            preserve_default=False,
        ),
    ]
