# Generated by Django 4.2.1 on 2023-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_alter_category_title_alter_region_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
