# Generated by Django 4.2.1 on 2023-05-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_company_topvacancy_alter_vacancy_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topvacancy',
            old_name='title',
            new_name='vacancy',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='vacancy.region', to_field='state'),
        ),
    ]
